In [1]:
pythonList = [1,9,8,3]
print(pythonList)

[1, 9, 8, 3]


In [2]:
import numpy as np
nparray = np.array(pythonList)
nparray

array([1, 9, 8, 3])

In [4]:
a = nparray +10
a

array([11, 19, 18, 13])

In [6]:
print(a.shape)
print(a.dtype)

(4,)
int32


In [8]:
b=np.array([1.0,2.0,3.0,4.0])
b
print(b.shape)
print(b.dtype)

(4,)
float64


In [15]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
c
print(c.shape)
print(c.dtype)

(3, 3)
int32


In [22]:
x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [23]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [33]:
d = np.array([(1,2,3),(4,5,6)])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
d.reshape(3,2)
print(d)

[[1 2 3]
 [4 5 6]]


In [35]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.52815631 5.26160818 4.64993537 5.02384518 5.14594028 6.03227518
 5.33327349 5.13571874 4.92673566 5.40648656]


In [39]:
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
f = np.arange(1,11)
print(f)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
g = np.arange(1,21,2)
print(g)

[ 1  3  5  7  9 11 13 15 17 19]


In [54]:
h = np.linspace(1,20,num=20,endpoint=False)
print(h)

[ 1.    1.95  2.9   3.85  4.8   5.75  6.7   7.65  8.6   9.55 10.5  11.45
 12.4  13.35 14.3  15.25 16.2  17.15 18.1  19.05]


In [55]:
i = np.logspace(1, 20, num=20)
print(i)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20]


In [56]:
q = np.matrix([(1,2,3),(4,5,6),(7,8,9)])
print(q)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
m = np.array([(1,2,3),(4,5,6)])
print(m)


[[1 2 3]
 [4 5 6]]


In [63]:
n = np.array([(1,2,3)],)
print(n)

[[1 2 3]]


In [66]:
print(m[0])
print(m[1])

[1 2 3]
[4 5 6]


In [73]:
print(m[0,:])


[1 2 3]


In [72]:
print(m[1,:])

[4 5 6]


In [75]:
print(m[:,0])


[1 4]


In [74]:
print(m[:,1])


[2 5]


In [76]:
print(m[:,2])

[3 6]


In [77]:
print(normal_array)


[5.52815631 5.26160818 4.64993537 5.02384518 5.14594028 6.03227518
 5.33327349 5.13571874 4.92673566 5.40648656]


In [78]:
print(np.max(normal_array))

6.032275179999085


In [80]:
print(np.min(normal_array))

4.6499353654461055


In [81]:
print(np.mean(normal_array))

5.244397494737221


In [82]:
print(np.median(normal_array))

5.2037742312332025


In [83]:
print(np.std(normal_array))

0.35499025521551936


In [88]:
f = np.array([1,2])
g = np.array([4,5])
print(f)
print(g)

[1 2]
[4 5]


In [89]:
np.dot(f,g)

14

In [90]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [91]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
np.linalg.matrix_rank(mx)

3